micropost/config/routes.rb
Micropost::Application.routes.draw do
  resources :mymicroposts

  resources :users

end

micropost/app/models/mymicropost.rb
class Mymicropost < ActiveRecord::Base
      validates :content, length: {maximum: 140}
      belongs_to :user
end

micropost/app/models/user.rb
class User < ActiveRecord::Base
      has_many :mymicroposts
end

micropost/app/controllers/mymicroposts_controller.rb
class MymicropostsController < ApplicationController
  before_action :set_mymicropost, only: [:show, :edit, :update, :destroy]

  # GET /mymicroposts
  # GET /mymicroposts.json
  def index
    @mymicroposts = Mymicropost.all
  end

  # GET /mymicroposts/1
  # GET /mymicroposts/1.json
  def show
  end

  # GET /mymicroposts/new
  def new
    @mymicropost = Mymicropost.new
  end

  # GET /mymicroposts/1/edit
  def edit
  end

  # POST /mymicroposts
  # POST /mymicroposts.json
  def create
    @mymicropost = Mymicropost.new(mymicropost_params)

    respond_to do |format|
      if @mymicropost.save
        format.html { redirect_to @mymicropost, notice: 'Mymicropost was successfully created.' }
        format.json { render action: 'show', status: :created, location: @mymicropost }
      else
        format.html { render action: 'new' }
        format.json { render json: @mymicropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mymicroposts/1
  # PATCH/PUT /mymicroposts/1.json
  def update
    respond_to do |format|
      if @mymicropost.update(mymicropost_params)
        format.html { redirect_to @mymicropost, notice: 'Mymicropost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @mymicropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mymicroposts/1
  # DELETE /mymicroposts/1.json
  def destroy
    @mymicropost.destroy
    respond_to do |format|
      format.html { redirect_to mymicroposts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mymicropost
      @mymicropost = Mymicropost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mymicropost_params
      params.require(:mymicropost).permit(:content, :user_id)
    end
end

micropost/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

micropost/app/helpers/mymicroposts_helper.rb
module MymicropostsHelper
end

micropost/app/helpers/users_helper.rb
module UsersHelper
end

micropost/app/views/mymicroposts/_form.html.erb
<%= form_for(@mymicropost) do |f| %>
  <% if @mymicropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mymicropost.errors.count, "error") %> prohibited this mymicropost from being saved:</h2>

      <ul>
      <% @mymicropost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

micropost/app/views/mymicroposts/edit.html.erb
<h1>Editing mymicropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @mymicropost %> |
<%= link_to 'Back', mymicroposts_path %>

micropost/app/views/mymicroposts/index.html.erb
<h1>Listing mymicroposts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @mymicroposts.each do |mymicropost| %>
      <tr>
        <td><%= mymicropost.content %></td>
        <td><%= mymicropost.user_id %></td>
        <td><%= link_to 'Show', mymicropost %></td>
        <td><%= link_to 'Edit', edit_mymicropost_path(mymicropost) %></td>
        <td><%= link_to 'Destroy', mymicropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mymicropost', new_mymicropost_path %>

micropost/app/views/mymicroposts/new.html.erb
<h1>New mymicropost</h1>

<%= render 'form' %>

<%= link_to 'Back', mymicroposts_path %>

micropost/app/views/mymicroposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @mymicropost.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @mymicropost.user_id %>
</p>

<%= link_to 'Edit', edit_mymicropost_path(@mymicropost) %> |
<%= link_to 'Back', mymicroposts_path %>

micropost/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

micropost/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

micropost/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

micropost/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

micropost/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>